# Generated by Django 3.0.2 on 2020-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(default='', max_length=50)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(default='', max_length=50)),
                ('phoneNo', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=5)),
                ('RH_type', models.CharField(max_length=5)),
                ('ques_1', models.CharField(default='', max_length=105)),
                ('ques_2', models.CharField(default='', max_length=105)),
            ],
        ),
    ]
