# Generated by Django 3.0.2 on 2020-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_blood', '0003_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestblood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('Phone_Number', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('blood_group', models.CharField(max_length=50)),
                ('RH_type', models.CharField(max_length=50)),
            ],
        ),
    ]
