# Generated by Django 3.0.2 on 2020-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_blood', '0004_requestblood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinvolved',
            name='phoneNo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
