# Generated by Django 3.0.2 on 2020-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_blood', '0005_auto_20200315_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinvolved',
            name='phoneNo',
            field=models.CharField(max_length=50),
        ),
    ]
