# Generated by Django 3.0.2 on 2020-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_blood', '0006_auto_20200315_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='phoneNo',
            field=models.CharField(max_length=50),
        ),
    ]
