# Generated by Django 3.0.2 on 2020-03-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_blood', '0007_auto_20200315_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='phoneNo',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='phoneNo',
            field=models.IntegerField(default=''),
        ),
    ]
