# Generated by Django 3.0.2 on 2020-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_blood', '0008_auto_20200315_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='phoneNo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='phoneNo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
