# Generated by Django 3.0.2 on 2020-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepal_blood', '0002_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('op', models.IntegerField(default=0)),
                ('on', models.IntegerField(default=0)),
                ('ap', models.IntegerField(default=0)),
                ('an', models.IntegerField(default=0)),
                ('bp', models.IntegerField(default=0)),
                ('bn', models.IntegerField(default=0)),
                ('abp', models.IntegerField(default=0)),
                ('abn', models.IntegerField(default=0)),
            ],
        ),
    ]
